tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        navy: "#071426",
        gold: "#8a6d00",
        "gold-soft": "#f4d77d",
        canvas: "#f8f9ff",
        ink: "#0d1c2f",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container": "#e6eeff",
        background: "#f8f9ff",
        "primary-fixed-dim": "#bcc7de",
        "on-surface": "#0d1c2f",
        "surface-dim": "#ccdbf4",
        "on-primary": "#ffffff",
        "on-background": "#0d1c2f",
        "tertiary-fixed-dim": "#c4c7c9",
        primary: "#091426",
        "outline-variant": "#c5c6cd",
        "on-surface-variant": "#45474c",
        "on-primary-container": "#8590a6",
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary-container": "#8d9092",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#fed65b",
        error: "#ba1a1a",
        outline: "#75777d",
        "primary-fixed": "#d8e3fb",
        "on-secondary": "#ffffff",
        "surface-tint": "#545f73",
        "surface-container-highest": "#d5e3fd",
        "on-secondary-fixed": "#241a00",
        "on-tertiary-fixed": "#191c1e",
        "surface-container-lowest": "#ffffff",
        secondary: "#735c00",
        surface: "#f8f9ff",
        "inverse-surface": "#233144",
        "on-error": "#ffffff",
        "surface-container-high": "#dde9ff",
        "inverse-primary": "#bcc7de",
        "inverse-on-surface": "#ebf1ff",
        "surface-variant": "#d5e3fd",
        "on-error-container": "#93000a",
        tertiary: "#111516",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-container": "#745c00",
        "on-tertiary-fixed-variant": "#444749",
        "primary-container": "#1e293b",
        "on-primary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#e0e3e5",
        "on-primary-fixed": "#111c2d",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#26292b"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-max": "1280px",
        lg: "2.5rem",
        xl: "4rem",
        base: "4px",
        xs: "0.5rem",
        gutter: "24px",
        sm: "1rem",
        md: "1.5rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  }
};
